language: android
dist: trusty
sudo: false
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.0

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

before_install:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - yes | sdkmanager "platforms;android-$ANDROID_API"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"

script: if [[ "$TRAVIS_TAG" ]]; then ./gradlew clean :app:assembleRelease --full-stacktrace; else ./gradlew clean test --full-stacktrace; fi

branches:
  except:
    - images
    - gh-pages
    - travis-build
    - i18n

notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:BPPLJNqX4mxGp8h2lkkotgNn
    template:
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: ''%{commit_subject}''>)  by
        %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check
        details>.'

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.android/build-cache"
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_script:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

after_success:
  - chmod +x ./publish_apk.sh; ./publish_apk.sh
